### ISSUE TITLE
I would love to work on the front-end part

### ISSUE THREAD

**Issue by Shwetang550** [purnima143/Kurakoo#10]
As a GSSoC'21 participant I would love to make my contributions by making some of the landing pages and components same as the figma slides for the Kurakoo :)

**Comment by aarushi31** [comment]
Hi I'm a GSSoc'21 participant. I would like to contribute to the front end part. Do you guys have any discord server for this project?

**Comment by Amit366** [comment]
Hi I'm a GSSoc'21 participant. I would like to contribute to the front end part.

**Comment by purnima143** [comment]
@Shwetang550 @Amit366 @aarushi31 Ya thanks for showing your interest in this project.You guys can create an issue and start working
