### ISSUE TITLE
error is not handled in case of database connection

### ISSUE THREAD

**Issue by abhay27chauhan** [purnima143/Kurakoo#103]
## Proposal

You have not handled the error -> catch statement missing

1.  Your code -> 

mongoose.connect(
  process.env.MONGO_URL,
    {
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useCreateIndex: true,
    }
  )
  .then(() => {
    console.log("database connected");
  });

2. My Suggestion ->

    mongoose.connect(
      process.env.MONGO_URL,
        {
          useNewUrlParser: true,
          useUnifiedTopology: true,
          useCreateIndex: true,
        }
      )
      .then(() => {
        console.log("database connected");
      })
      .catch(error => {         // line missing
       console.log(error)
       })

**Comment by codewithvk** [comment]
@abhay27chauhan Do you want to work on it?

**Comment by tend2infinity** [comment]
Hey there! I'm a GSSOC participant can I work on this issue since no one else is assigned?

**Comment by abhay27chauhan** [comment]
> @abhay27chauhan Do you want to work on it?

yes, i want to work on this one

**Comment by codewithvk** [comment]
@tend2infinity go ahead! Also, add `red CLI` for the error part.

@abhay27chauhan we are assigning issues based on first come. You can look/create some other issue.

**Comment by abhay27chauhan** [comment]
> @tend2infinity go ahead! Also, add `red CLI` for the error part.
> 
> @abhay27chauhan we are assigning issues based on first come. You can look/create some other issue.

no preblem, But i am the first one. Because this issue is opened by me

**Comment by codewithvk** [comment]
@abhay27chauhan next time please add-in issue so we can work smoothly :)
