### ISSUE TITLE
Frontend: Notification Page

### ISSUE THREAD

**Issue by Aniket1103** [purnima143/Kurakoo#106]
## Proposal

I will like to work on the frontend part of the Notification Page for the Project as a part of gssoc21.
Kindly assign it to me.

**Comment by ir2010** [comment]
Would you like to code the page or create a new design? If you want to code the frontend of the page, please let us know the design you'll be following.

**Comment by Aniket1103** [comment]
Yes, I will be considering the coding part
and I was thinking of following the design present in the Figma file for the notification page.
Is that fine?

**Comment by Aniket1103** [comment]
@ir2010 So should I start working on it?
Could you please assign it to me?

**Comment by ir2010** [comment]
@Aniket1103 go ahead

**Comment by Aniket1103** [comment]
Ok, Thank you maam!
