### ISSUE TITLE
Front end: Working on a add a question page

### ISSUE THREAD

**Issue by riddhisiddarkar** [purnima143/Kurakoo#108]
Hey @purnima143 ! I just saw that the design for adding a question has been added. Could I code the front-end for it in react? I'm a gssoc '21 participant and it would be great if you could assign me this issue. 

Thank you so much for your time.

**Comment by ir2010** [comment]
@riddhisiddarkar go ahead

**Comment by riddhisiddarkar** [comment]
Hey! I have made the pull request #124 for the code and also added a modal to insert a link.
