### ISSUE TITLE
Categorization of questions based on the different subjects.  

### ISSUE THREAD

**Issue by BharatiSukanya** [purnima143/Kurakoo#109]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by BharatiSukanya** [comment]
A feature to put particular subject questions in the respective category. 
This requires a bar at the top of the screen to select particular subject questions to either, answer, view, or discuss.

**Comment by purnima143** [comment]
@BharatiSukanya  Wanna work on this issue?

**Comment by nishihere19** [comment]
Can I work on this issue under gssoc'21?

**Comment by BharatiSukanya** [comment]
@purnima143 sure will work on it.

**Comment by purnima143** [comment]
@BharatiSukanya assigned
