### ISSUE TITLE
Redirecting user to the feed page once a user is successfully logged in

### ISSUE THREAD

**Issue by tend2infinity** [purnima143/Kurakoo#112]
## **Introduction**
Hii, I am a Gssoc participant and I would like to work diligently upon the issue explained below, please assign that to me.

## **Description**
See, right now the logic written for the login component in the client-side does not redirect the user upon getting successfully signed in (after going through that API call), he just stays in the login page after getting signed in. I want that if a user is successfully signed in then he must get redirected to the feed page. Also if there occurs a new user signup then also we need to redirect the user to the home page, so that he can log in with his credentials.

## **Solution**
Since all the components in app.js are already wrapped in BrowserRouter so, I can use the useHistory() hook within the components to redirect to the feed component or to any other components.

**Comment by ir2010** [comment]
@tend2infinity go ahead
