### ISSUE TITLE
Making Homepage responsive and adding correct content

### ISSUE THREAD

**Issue by hardik7e** [purnima143/Kurakoo#116]
## **Would like to make following Enhancements**
- Make Homepage responsive
- add correct content on homepage

**Comment by purnima143** [comment]
@hardik7e  just wait for a while. We are working on the homepage. Once that's get done you can start working on this issue.

**Comment by hardik7e** [comment]
Okay

**Comment by vedant-jain03** [comment]
I want to work on this issue.

**Comment by purnima143** [comment]
@hardik7e wanna carryon with this issue?

**Comment by vedant-jain03** [comment]
@purnima143 I want to work in this issue

**Comment by hardik7e** [comment]
@purnima143 yes

**Comment by purnima143** [comment]
> @purnima143 I want to work in this issue

@vedant-jain03 You can try to work on other issues or create new one
