### ISSUE TITLE
Adding meta http-equiv content type

### ISSUE THREAD

**Issue by Diksha-11** [purnima143/Kurakoo#117]
I would like to add a meta tag containing attribute "http-equiv" and 'content-type" in /client/public/index.html.

As "http-equiv" attribute set is similar to the http header.Thus, it should be ther in the Kurakoo.
Along with that "http-equiv" with "content-type" allows us to specify the media type & character set.

Thus ,I request @maw1a  @ir2010 @codewithvk to please /assign me this issue.

**Comment by codewithvk** [comment]
@Diksha-11 hey can you please describe what does need of `http-equiv` for our application?

**Comment by Diksha-11** [comment]
@codewithvk , meta http-equiv attribute is used to run the http content. It allows to run only what is present inside the mentioned content. 

In the about section of kurakoo, It is written that: "Kurakoo is an online community of people providing answers to questions just like Quora site."

Even quora has this meta attribute (Saw when I inspect Quora), that's why I felt that it should be included in kurakoo too.

Since I'm a beginner, please correct me if I'm wrong somewhere.

**Comment by codewithvk** [comment]
@Diksha-11 ok greate! Go ahead.

**Comment by Diksha-11** [comment]
@codewithvk sir, your name is showing in assignees.

**Comment by codewithvk** [comment]
@Diksha-11 Apologies for the mistake

**Comment by Diksha-11** [comment]
@codewithvk no problem sir.
