### ISSUE TITLE
User and Admin add 

### ISSUE THREAD

**Issue by VishalRajai41** [purnima143/Kurakoo#120]
## **Describe the bug**
1). Add the user sign-in for server-side code.
2). Add the admin sign-in and signup for server-side code.
- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by himanshujaidka** [comment]
@VishalRajai41 is it necessary to add admin?

**Comment by VishalRajai41** [comment]
Yes of course. Without admin how can you handle website?

**Comment by aniketlodh** [comment]
How about adding a secret code input in the login and signup form to check whether the user is the admin?
