### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by Sloth-Panda** [purnima143/Kurakoo#13]
This project lacks a code of conduct file so would like to add that.

please assign me as part of gssoc'21.

**Comment by subhangi2731** [comment]
can you please assign this to me?

**Comment by Sloth-Panda** [comment]
@purnima143

**Comment by purnima143** [comment]
@subhangi2731 You can go ahead with this issue

**Comment by purnima143** [comment]
@Sloth-Panda  You are assigned for another issue, so I am giving this chance to @subhangi2731

**Comment by Sloth-Panda** [comment]
@purnima143 you can assign me if the other person is not active.!

**Comment by rajeshpanjiyar** [comment]
I want to work on this so I request you to assin this me too. I am a participant in GSSOC'21.

**Comment by subhangi2731** [comment]
I am working om this

**Comment by subhangi2731** [comment]
@purnima143 Thank you so much and I will make a pr by today
