### ISSUE TITLE
Remove warnings 

### ISSUE THREAD

**Issue by Subham142** [purnima143/Kurakoo#130]
## **Describe the bug**
few warnings are shown in the homepage.s

## **Screenshots**

![Screenshot (41)](https://user-images.githubusercontent.com/60570595/112263671-b33bf980-8c95-11eb-8ee7-bb85d505820a.png)

**Comment by Subham142** [comment]
@codewithvk  please assign it to me add add the lables

**Comment by codewithvk** [comment]
@Subham142 go ahead!
