### ISSUE TITLE
Sign up button is not visible in header

### ISSUE THREAD

**Issue by akshay1027** [purnima143/Kurakoo#132]
## **Describe the bug**

- The Signup Button near Signin Button in the header is not visible in the desktop view!

## **Screenshots**

![2021-03-25](https://user-images.githubusercontent.com/65683151/112422006-31f86b80-8d56-11eb-87c3-2aeb400d22b8.png)

**Comment by ishikalohia** [comment]
I would like to work on this issue under gssoc 21.

**Comment by akshay1027** [comment]
hey, @ishikalohia I wanted to work on this, hence created this issue! :)

**Comment by codewithvk** [comment]
@akshay1027 go ahead!

@ishikalohia you can look at another issue :)

**Comment by ishikalohia** [comment]
Hii sure :)
