### ISSUE TITLE
Feed Page

### ISSUE THREAD

**Issue by Sristi27** [purnima143/Kurakoo#134]
## **Describe the bug**

- In feed page navbar is not visible.

## **Possible solution**

- I can work on this issue to fix it.

## **Screenshots**
![Screenshot 2021-03-26 at 12 00 01 PM](https://user-images.githubusercontent.com/53037053/112591727-ce8c3d80-8e2a-11eb-9525-99db65bc7433.png)

**Comment by codewithvk** [comment]
@Sristi27 go ahead!

**Comment by Sristi27** [comment]
@codewithvk I have created the PR. Do look into it and review it!

**Comment by codewithvk** [comment]
@Sristi27 could you please mention with the issue?

**Comment by Sristi27** [comment]
I have mentioned the issue in the previous comment only.After that only I was assigned I believe!

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.
