### ISSUE TITLE
The form in the signIn page is too simple. I would like to make it more attractive.

### ISSUE THREAD

**Issue by ChitvanRamani22** [purnima143/Kurakoo#149]
## **Describe the bug**
SignIn page too simple
- A clear an
@purnima143 could you please assign me this under gssoc'21.
![Screenshot (468)](https://user-images.githubusercontent.com/68965499/114139741-0a47fc80-992d-11eb-9358-2c7212e624eb.png)

d concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by purnima143** [comment]
@ChitvanRamani22 What changes will you do here?

**Comment by ChitvanRamani22** [comment]
Something like this with proper validations and also will make it look more attractive by providing border radius and border color.

https://user-images.githubusercontent.com/68965499/114173675-265f9400-9955-11eb-8bb2-35f737921e9e.mp4

**Comment by purnima143** [comment]
@ChitvanRamani22 Validation part?

**Comment by ChitvanRamani22** [comment]
@purnima143 email validation like those @ nd all validations that are required for a correct email.
