### ISSUE TITLE
Backend: Setup a response handler for the API

### ISSUE THREAD

**Issue by Mayank0255** [purnima143/Kurakoo#15]
The response handler is a helper function and for that, we can put this under the helper's directory.
The benefit of this is for front-end developers working on this project, for which fetching appropriate data from the endpoint would be easier and well structured.

The Response Handler should be of this structure:

```
{
    success (Boolean): If the data is successfully retrieved then it should be "true", otherwise it should be "false".
    code (Integer): Appropriate status code of the API call like 501 for bad request, 200 for OK, etc.
    message (String): Message describing the action performed like "Post Created Successfully", "Failed to Create the Post", etc.
    data (Object): Return the data in this field if retrieved successfully, otherwise it should be "null"
}
```

Can I work on this?

**Comment by Mayank0255** [comment]
Can you assign it to me under GSSOC'21? @purnima143

**Comment by Mayank0255** [comment]
@himanshujaidka actually the helper directory will be in the src of server directory which is the backend directory and the helpers directory will be in both client and server as later while deploying the app we would need to create separate mono repos of the api and the client

**Comment by himanshujaidka** [comment]
okay

**Comment by Mayank0255** [comment]
@purnima143 could you assign this to me and add the relevant labels too?
