### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by vedant-jain03** [purnima143/Kurakoo#153]
## **Is your feature request related to a problem? Please describe.**

- I want to add preloader to the website.

## **Describe the solution you'd like**

- I will apply it using html,css and js.

**Comment by codewithvk** [comment]
@vedant-jain03 We are using React Js for the frontend, So if you can do it in React js then I can assign you!

**Comment by vedant-jain03** [comment]
Offcourse sir I can do it in react js
I learned react only for my frondend library
Please assign me

**Comment by vedant-jain03** [comment]
Offcourse sir I can do it in react js
I learned react only for my frondend library
Please assign me

**Comment by vedant-jain03** [comment]
Offcourse sir I can do it in react js
I learned react only for my frondend library
Please assign me

**Comment by vedant-jain03** [comment]
https://user-images.githubusercontent.com/76901313/114297933-46b45d80-9ad1-11eb-9633-be4359257b9d.mp4


@codewithvk I have added sample video of Preloader that I made
I use suspense,lazy to fetch and show preload until all the data is being loaded
If you like the theme I will add and make PR of it

**Comment by purnima143** [comment]
@vedant-jain03 go ahead
