### ISSUE TITLE
Want to add Hovers to all buttons

### ISSUE THREAD

**Issue by vedant-jain03** [purnima143/Kurakoo#159]
## **Is your feature request related to a problem? Please describe.**

- The UI looks great but addition of hovering effect will give it more better look and UI.

## **Describe the solution you'd like**

- Want to add hover effect to buttons of all pages 

![bandicam 2021-04-11 21-57-55-811](https://user-images.githubusercontent.com/76901313/114312683-23a99e00-9b11-11eb-8169-4f1aa014fec9.jpg)

**Comment by vedant-jain03** [comment]
If valid issue assign me @purnima143 @codewithvk

**Comment by subhasmitapradhan** [comment]
I would like to work on this issue as I have prior experience with this website as well as I know the colours and themes that will suit it the best.

**Comment by ir2010** [comment]
@vedant-jain03 go ahead
