### ISSUE TITLE
Frontend : Setting up react redux

### ISSUE THREAD

**Issue by sachinsom93** [purnima143/Kurakoo#16]
## Description

As the project is in it's initial phase so it would be  helpful for further state management task if we can setting up react-redux now.

## Additional 

@purnima143, if you approve this issue, could you please assign me this.
I would love to contribute to this project under GSSOC2021.

**Comment by purnima143** [comment]
@sachinsom93  Go ahead

**Comment by sachinsom93** [comment]
Closing this issue as task is done.
