### ISSUE TITLE
font selection is not appropriate

### ISSUE THREAD

**Issue by himanshujaidka** [purnima143/Kurakoo#162]
Need to change the font of the website, need a more professional way 
![Screenshot (203)](https://user-images.githubusercontent.com/58654018/114355012-986dee00-9b8c-11eb-944e-85df15bfaacf.png)

**Comment by ir2010** [comment]
which font you want to use?

**Comment by himanshujaidka** [comment]
> which font you want to use?

like in this all things are looking similar, I am unable to differentiate between the heading, questions, answers. For answers, we should keep the font size small, or it should differ from the questions, and everywhere there is a bold text which is not a good practice.

**Comment by himanshujaidka** [comment]
but now it's seems good

**Comment by himanshujaidka** [comment]
![Screenshot (206)](https://user-images.githubusercontent.com/58654018/114554837-c171aa00-9c84-11eb-9076-e0999015e632.png)
