### ISSUE TITLE
Bug: Objects are not valid as a React child (found: [object Promise]).

### ISSUE THREAD

**Issue by himanshujaidka** [purnima143/Kurakoo#164]
notification & addaquestion routes are not working in the frontend.
![Screenshot (204)](https://user-images.githubusercontent.com/58654018/114357502-6f9b2800-9b8f-11eb-82d6-7dd42cf060d3.png)

**Comment by codewithvk** [comment]
@himanshujaidka Do you want to work on it?

**Comment by himanshujaidka** [comment]
> @himanshujaidka Do you want to work on it?
No, sorry

**Comment by Subham142** [comment]
@purnima143  assign it to me
