### ISSUE TITLE
Backend: signup/login API

### ISSUE THREAD

**Issue by himanshujaidka** [purnima143/Kurakoo#17]
for these APIs, we need to first connect the database, so I would be happy if this would assign to me.

**Comment by udaymittal7** [comment]
I would like to work on this API.

**Comment by himanshujaidka** [comment]
@vijayjoshi16 you could collaborate here :)

**Comment by vijayjoshi16** [comment]
Ok @himanshujaidka :)

**Comment by himanshujaidka** [comment]
I am working on signup API

**Comment by vijayjoshi16** [comment]
Ok I'll start working on the user schema soon....

**Comment by himanshujaidka** [comment]
> Ok I'll start working on the user schema soon....

I mean all files that are necessary for making signup API and without schema file API will not work if you are interested then pls work on login API

**Comment by vijayjoshi16** [comment]
"without schema file API will not work"....I understood this point.....
"if you are interested then pls work on login API"....here I'm confused whether to work on schema file or login API

**Comment by kaffan** [comment]
> @vijayjoshi16 you could collaborate here :)
can you give me some task?
