### ISSUE TITLE
× Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.

### ISSUE THREAD

**Issue by Subham142** [purnima143/Kurakoo#172]
Add a question page

![Screenshot (77)](https://user-images.githubusercontent.com/60570595/114599845-44105e80-9cb1-11eb-93d7-2c8fa567b09e.png)

**Comment by Subham142** [comment]
@codewithvk @purnima143  assign it to me

**Comment by codewithvk** [comment]
Hey @Subham142 , This issue has been already solved by @purnima.
