### ISSUE TITLE
edit question (backend)

### ISSUE THREAD

**Issue by mitalirs** [purnima143/Kurakoo#176]
## **edit question (backend)**

- Once a user creates a question there is no feature that allows him/her to edit it

## **Solution**

- An 'editQuestion' request that will allow the user to edit the question that was created by them (requiresSignIn)
- I will work on the backend logic

@purnima143, @codewithvk can you please assign this issue to me?

**Comment by codewithvk** [comment]
@mitalirs Go ahead!
