### ISSUE TITLE
 Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.

### ISSUE THREAD

**Issue by himanshujaidka** [purnima143/Kurakoo#178]
## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot (209)](https://user-images.githubusercontent.com/58654018/114665071-32af6c80-9d1a-11eb-9fb5-fa497d462ec3.png)

pls assign this to me:)

**Comment by Subham142** [comment]
@himanshujaidka  I think this was solved last night

**Comment by himanshujaidka** [comment]
> @himanshujaidka I think this was solved last night
> did you fetch it?

yes, sorry, confusion with multiple branches
