### ISSUE TITLE
Night Mode Feature

### ISSUE THREAD

**Issue by vedant-jain03** [purnima143/Kurakoo#181]
## **Is your feature request related to a problem? Please describe.**

- I want to give this project feature of night mode.

## **Describe the solution you'd like**

- I will give a checkbox like button by enabling it the color theme of the website changes to dark mode.

**Comment by vedant-jain03** [comment]
@purnima143 If valid please assign and also recommend me with the main color theme replacing the orange texture.

**Comment by ir2010** [comment]
@purnima143 please suggest him about the color theme

**Comment by purnima143** [comment]
@vedant-jain03 use brown color as background for dark theme...and for font use more up of orange or creame or white colors
