### ISSUE TITLE
Front end: SignUp form

### ISSUE THREAD

**Issue by vijayjoshi16** [purnima143/Kurakoo#19]
# Context
Whenever a new user visits the website, the very first thing he/she would like do in order to get started will be to sign up. Hence a SignUp form must be created so that new users can register themselves and start using the features of the website.

# Description
Create a signup form for the website which will take the following details as input:
- Name
- Email id
- Password
- Confirm password
- Year/Sem
- College
- Signup button

Show appropriate message to the user on invalid email, not matching passwords and other cases whenever necessary.

# Acknowledgements/References
Issue #3 for the input content for sign up form

**Comment by purnima143** [comment]
Sure @vijayjoshi16  I will asssign you

**Comment by purnima143** [comment]
@vijayjoshi16 Wait! I will share the design of the signup form, it's not yet completed

**Comment by vijayjoshi16** [comment]
Ok👍

**Comment by purnima143** [comment]
## Sign Up page Design
![Signup-Kurakoo](https://user-images.githubusercontent.com/57852378/110688272-6709a780-8207-11eb-9f74-c4dc7fe65ed7.png)

## Below is the drive link that has required assets
https://drive.google.com/drive/folders/1S-Mx9Hsrf1GdnUFLCQSWwH-NsejZbVmi?usp=sharing
