### ISSUE TITLE
Want to add sticky social media links menu 

### ISSUE THREAD

**Issue by vedant-jain03** [purnima143/Kurakoo#204]
## **Is your feature request related to a problem? Please describe.**

- Want to add sticky social media menu 

## **Describe the solution you'd like**

- I will make sticky navbar like menu floating to left of the screen and showing an options to social media handles.

**Comment by codewithvk** [comment]
Hey, @vedant-jain03  Can you describe more?

Also please mention do you want to work on it or not by [Yes or no].

**Comment by vedant-jain03** [comment]
> Hey, @vedant-jain03 Can you describe more?
> 
> Also please mention do you want to work on it or not by [Yes or no].

![bandicam 2021-04-18 12-09-13-235](https://user-images.githubusercontent.com/76901313/115136676-fb54fe80-a03e-11eb-890c-03c4c96db4b0.jpg)
 
I will give colors according to our theme that is orange type.

**Comment by codewithvk** [comment]
@vedant-jain03 LG :) Go ahead!
