### ISSUE TITLE
Refactor Component File.

### ISSUE THREAD

**Issue by codewithvk** [purnima143/Kurakoo#208]
## **Is your feature request related to a problem? Please describe.**

- In `client/src/` There are two folders that have components. 

## **Describe the solution you'd like**

- We need to merge into one folder called `components` and remove the extra folder also change the import link accordingly.

**Comment by ChitvanRamani22** [comment]
@codewithvk i would like to take this up.

**Comment by himanshujaidka** [comment]
@codewithvk linked pr #211

**Comment by himanshujaidka** [comment]
@ChitvanRamani22 sorry I forgot to leave a comment, if you are interested then pls have a look at #187, it is similar to this

**Comment by ChitvanRamani22** [comment]
@himanshujaidka 
Have u worked on it without getting assigned.

**Comment by himanshujaidka** [comment]
> @himanshujaidka
> Have u worked on it without getting assigned.

sorry, I am closing my pr, if you are interested then pls go-ahead

**Comment by codewithvk** [comment]
> sorry, I am closing my pr, if you are interested then pls go-ahead

If you un-assigned yourself, Then please inform the mentor.

**Comment by codewithvk** [comment]
@ChitvanRamani22 Go ahead!

**Comment by himanshujaidka** [comment]
> > sorry, I am closing my pr, if you are interested then pls go-ahead
> 
> If you un-assigned yourself, Then please inform the mentor.

ok
