### ISSUE TITLE
Front end: Feed Page

### ISSUE THREAD

**Issue by Aniket1103** [purnima143/Kurakoo#21]

**Comment by Aniket1103** [comment]
I will like to work on the front end of the feed page as a part of GSsoc21.
Please assign it to me.

**Comment by purnima143** [comment]
@Aniket1103 Ya go ahead

**Comment by Aniket1103** [comment]
@purnima143 Please let me know, In which directory should I keep the feedpage.js page and other components like the navigation bar, sidebars, and feed component?

**Comment by purnima143** [comment]
Client--->src--->Create folder Component--->place feed.js inside Component folder

And ya your design is fine, go with that design for now.

**Comment by Aniket1103** [comment]
Ok, thanks!

**Comment by JASHANJOT7KAUR** [comment]
I would like to work on this issue, kindly assign it to me.

**Comment by purnima143** [comment]
@JASHANJOT7KAUR  Already assigned to @Aniket1103  . You can try to find out other issues.

**Comment by Aniket1103** [comment]
@purnima143 I needed the .svg file of the Kurakoo logo
And I am not able to copy or download it from the Figma file
What should I do?

**Comment by purnima143** [comment]
I will share

**Comment by purnima143** [comment]
https://drive.google.com/drive/folders/1S-Mx9Hsrf1GdnUFLCQSWwH-NsejZbVmi

**Comment by Aniket1103** [comment]
thank you

**Comment by kanishkaa24** [comment]
Hello Mam! Can I work on this?
