### ISSUE TITLE
buggy homepage.js

### ISSUE THREAD

**Issue by himanshujaidka** [purnima143/Kurakoo#210]
![Screenshot (214)](https://user-images.githubusercontent.com/58654018/115136804-cc8b5800-a03f-11eb-8513-faabd04c8e63.png)

I am not interested to work on this bug

**Comment by himanshujaidka** [comment]
wants to work

**Comment by Subham142** [comment]
@codewithvk  when i fix this this another error rises up
![Screenshot (102)](https://user-images.githubusercontent.com/60570595/115148359-cb2c5080-a07c-11eb-9363-e08a518dda6b.png)

**Comment by Subham142** [comment]
I'm not able to see error here, if you could suggest me

**Comment by codewithvk** [comment]
@Subham142 @himanshujaidka now, can you confirm me all thing working fine or not?

**Comment by himanshujaidka** [comment]
@codewithvk yes working fine now
