### ISSUE TITLE
A group based on college of the user

### ISSUE THREAD

**Issue by bug-debug-done** [purnima143/Kurakoo#22]
I am a GSSoC'21 participant
There will be groups for different colleges. When a user will sign up He/She can join that group. It can act as an alumni network and will help students to get a better insight into the placements in their college. Alumni can also share how they applied for it and how they prepared. It will come under the Placement category. It will help to clear the doubts in a better way.

**Comment by himanshujaidka** [comment]
@bug-debug-done this project is in its initial stage, and the feature you are requested will be implemented later, once the project will be in its working mode.

**Comment by bug-debug-done** [comment]
> @bug-debug-done this project is in its initial stage, and the feature you are requested will be implemented later, once the project will be in its working mode.

ok
