### ISSUE TITLE
delete question (backend)

### ISSUE THREAD

**Issue by mitalirs** [purnima143/Kurakoo#227]
## delete question (backend)

- Once a user creates a question there is no feature that allows him/her to delete the question posted

## **Solution**

- A 'deleteQuestion' request that will allow the user to delete the question that was created by them (requiresSignIn)
- As the user will delete the question (by passing question id as parameter) all the answers with 
questionId = Id of question which the user wishes to delete 
will be also removed from the database
- I will work on the backend logic

@purnima143, @codewithvk can you please assign this issue to me

**Comment by codewithvk** [comment]
@mitalirs go ahead!
