### ISSUE TITLE
Frontend : Sign In Page | GSSOC21

### ISSUE THREAD

**Issue by shawavisek35** [purnima143/Kurakoo#23]
# Context
A Sign In page for the existing user.

# Description
Create a sign in form for the website which will take the following details as input:

* Email id
* Password
* Sign In button
* Social Media Sign In buttons it required.

Show an appropriate message to the user if the user details do not exist in the database and ask them to create an account first.

@purnima143 could you please review this issue and assign it to me?

**Comment by purnima143** [comment]
@shawavisek35  I will assign this issue

**Comment by shawavisek35** [comment]
One question @purnima143  : I can see that the design of the sign in page in figma is not yet completed so should I wait for that to be completed or I can start and design it in my own way.

**Comment by purnima143** [comment]
@shawavisek35 Wait for today, Once I will share you can start working on the development

**Comment by purnima143** [comment]
## Sign In page Design

![Signin-Kurakoo](https://user-images.githubusercontent.com/57852378/110688257-640eb700-8207-11eb-9684-9b9e7e7c44b1.png)
## Below is the drive link that has required assets
https://drive.google.com/drive/folders/1S-Mx9Hsrf1GdnUFLCQSWwH-NsejZbVmi?usp=sharing

**Comment by shawavisek35** [comment]
Thanks
By the way the design is really nice.

**Comment by purnima143** [comment]
@shawavisek35 Can you use a material UI framework for designing the page?

**Comment by purnima143** [comment]
@shawavisek35  go through #42 pr once

**Comment by shawavisek35** [comment]
> @shawavisek35 Can you use a material UI framework for designing the page?

Yup I am using the material UI framework only
