### ISSUE TITLE
fields are missing in frontend

### ISSUE THREAD

**Issue by himanshujaidka** [purnima143/Kurakoo#233]
first name, Lastname fields are missing in the frontend and some fields are also missing in the schema file as well.

###### Do you want to work on this issue - [Yes/No]
@codewithvk @purnima143 pls assign this issue to me
![Screenshot (215)](https://user-images.githubusercontent.com/58654018/115358794-a7335100-a1db-11eb-94ea-aff82849de07.png)

**Comment by codewithvk** [comment]
@himanshujaidka request to you, without assigning don't make PR.

**Comment by himanshujaidka** [comment]
> @himanshujaidka request to you, without assigning don't make PR.

sorry, I will take care of it

**Comment by himanshujaidka** [comment]
@codewithvk pls assign now
