### ISSUE TITLE
Minor grammatical errors in the README.md file.

### ISSUE THREAD

**Issue by anirudhsai20** [purnima143/Kurakoo#24]
There are minor grammatical mistakes that needs to be corrected which will enhance the file.

**Comment by anirudhsai20** [comment]
Hi @purnima143 . Please allow me to work on this under GSSOC.

**Comment by purnima143** [comment]
@anirudhsai20  Go ahead

**Comment by kanishkaa24** [comment]
Hello Mam! Can I work on this?

**Comment by niyatitotala** [comment]
Hello, Can I work on this? @purnima143

**Comment by 435akashjha** [comment]
@purnima143 Please assign this issue to me I am beginner and would like to contribute to this project
