### ISSUE TITLE
Answering a valid question

### ISSUE THREAD

**Issue by mitalirs** [purnima143/Kurakoo#240]
## Answering a valid question

- Currently while creating an answer a user enters the questionId as a string which is sent using the POST request. There is a possibility that a user can enter a wrong questionId 

## **Solution**

- The questionId sent as a part of the POST request (createAnswer) should be verified, only then a user should be allowed to answer. I will add the verification part in the createAnswer route

I wish to work on the backend logic of this issue
@purnima143, @codewithvk can you please assign this issue to me?

**Comment by codewithvk** [comment]
#239 both assign you and please make one PR for both with level 2

**Comment by mitalirs** [comment]
Sure, thank you @codewithvk for assigning the issues!
