### ISSUE TITLE
delete profile (backend)

### ISSUE THREAD

**Issue by mitalirs** [purnima143/Kurakoo#249]
## **delete profile (backend)**

- Currently, a user cannot delete his/her profile. I wish to create a route(requiresSignIn) for the same

## **Solution**

- Whenever a user will delete his/her profile the User collection will get updated
- All the answers posted by that user will be deleted
- The questions would not be deleted instead the createdBy field in those questions will have a value = id of a default user (with username = user123)
- The default user will be created by this route if it is not in the User collection and if the User collection already has it, the route will assign the id accordingly to the createdBy field of those questions

I wish to work on the backend part of this

@purnima143, @codewithvk can you please assign this issue to me

**Comment by purnima143** [comment]
@mitalirs go ahead
