### ISSUE TITLE
A Very First Welcome Page of this website with interactive {html,css,javascript,react}

### ISSUE THREAD

**Issue by ASHISH-GITHUB2495** [purnima143/Kurakoo#25]
contents:-
1. login option.
2. create account option.
    - both 1 and 2 will redirect to login/signup page
3. 3.contact option which you will edit later.
4. Animated welcome page of this website.

**Comment by ASHISH-GITHUB2495** [comment]
I am already working on it ... please assign it to me mam.
Thank you...

**Comment by purnima143** [comment]
@ASHISH-GITHUB2495  Go ahead

**Comment by purnima143** [comment]
@ASHISH-GITHUB2495 May I know your process, how much you had done?

**Comment by ASHISH-GITHUB2495** [comment]
> @ASHISH-GITHUB2495 May I know your process, how much you had done?

All Html and basic things have done...just working with css now.. soon it will be done

**Comment by aqua0** [comment]
Is this issue done?
If not i want to work on this issue

**Comment by ASHISH-GITHUB2495** [comment]
> Is this issue done?
> If not i want to work on this issue

Yes , i have done it and generated pull request , you can check it,
