### ISSUE TITLE
upvote/downvote answer (backend)

### ISSUE THREAD

**Issue by mitalirs** [purnima143/Kurakoo#250]
## **upvote/downvote answer**

- Currently, a user cannot upvote/downvote any answer. I wish to create 2 separate routes (requiresSignIn) for this 

## **Solution**

- 2 int fields, upvotes and downvotes in the answer model (to keep a count)
- 2 array fields called upvotedAns and downvotedAns in the user model. They will contain the ids of the answers the user has upvoted/downvoted
- a user can either upvote or downvote an answer
- a user can upvote or downvote any answer only once

I wish to work on the backend part of this 
@purnima143, @codewithvk can you please assign this issue to me

**Comment by purnima143** [comment]
@mitalirs You can start working in this issue

**Comment by subhangi2731** [comment]
@purnima143 please assign this issue to me
