### ISSUE TITLE
fetch answers (backend)

### ISSUE THREAD

**Issue by mitalirs** [purnima143/Kurakoo#251]
## **fetch answers**

- Currently, there is no route that enables a user to fetch all the answers to a particular question

## **Solution**

- Create a request (requiresSignIn) which will take the question id as a parameter and fetch all the answers to that question

I wish to work on the backend part of this
@purnima143, @codewithvk can you please assign this issue to me?

**Comment by codewithvk** [comment]
@mitalirs Humbly request to you, please don't mention in every place. If you did not get any response in two or more days then you can mention us. Mentors are for you. Hope you understand :)

**Comment by mitalirs** [comment]
> @mitalirs Humbly request to you, please don't mention in every place. If you did not get any response in two or more days then you can mention us. Mentors are for you. Hope you understand :)

Sure, extremely sorry for the inconvenience that was caused!
