### ISSUE TITLE
Develop the Homepage of the site according to given UI

### ISSUE THREAD

**Issue by purnima143** [purnima143/Kurakoo#252]
## **Problem**
Currently, on our Kurakoo site, there is a lack of consistency in UI. All the contributors did a great job in designing but to follow one flow we have to change the UI that will give clarity to backend people also.

## **Possible solution**
- Below is the UI of the upcoming homepage.
- Let's use the **Material-UI** framework for the frontend. **Let's stick to one framework only.**

## **Screenshots**
![kurakoohm](https://user-images.githubusercontent.com/57852378/115721577-ce388100-a39b-11eb-9bf9-6a37227cd336.png)

## **Instructions**
- First, **collect all the assets required for designing, which will be in assets->Homepage->NewUI.**
- Add these fonts in the file if it's not there
   - For bold Heading: [Poppins](https://fonts.google.com/specimen/Poppins)
   - For paragraph:[Open sans](https://fonts.google.com/specimen/Open+Sans?query=open)
- Use colors: 
   - **Heading: #000 (black)& #E85D04**
   - **Paragraph:#594D52**
  
- Use **MATERIAL-UI Framework.**

 If you get any doubt ask mentors or me, we'll try to help you out.
😊😊

**Comment by vedant-jain03** [comment]
@purnima143 I want to work on this issue

**Comment by vedant-jain03** [comment]
I will also enable Dark Mode as I did before in Navbar section.
I just wanted to know that the vectors which @purnima143 Used above are available ?
If available it will be good for me

**Comment by vedant-jain03** [comment]
@purnima143 Could you please provide me with the vectors you have used in Design

**Comment by purnima143** [comment]
@vedant-jain03 All vectors, illustrations, icon, etc are present in **assets folder->NewUI folder->homepage folder**
