### ISSUE TITLE
Want to Re-edit Contributor section and new About us section in Home Page

### ISSUE THREAD

**Issue by vedant-jain03** [purnima143/Kurakoo#256]
## **Is your feature request related to a problem? Please describe.**

- Want to Re-edit Contributor section and new About us section in Home Page

## **Describe the solution you'd like**

- Want to Re-edit Contributor section and new About us section in Home Page

**Comment by purnima143** [comment]
only these two sections?

**Comment by vedant-jain03** [comment]
I just want Flow like
1. Welcome page as we have 
2. About Us page (Kurakoo Main Purpose)(Height 100vh)
3. Contributor Section(Kurakoo Collaborators and Contributors)(Height 60vh)
4. Footer

I also want to add Mentor Profile Card section but for this I will raise new issue and take it forward

**Comment by purnima143** [comment]
@vedant-jain03 #252 work on this issue
