### ISSUE TITLE
I want to add Dark Mode to New UI Home Page

### ISSUE THREAD

**Issue by vedant-jain03** [purnima143/Kurakoo#262]
## **Is your feature request related to a problem? Please describe.**

- I want to add Dark Mode to New UI Home Page

## **Describe the solution you'd like**

- I already did dark mode in recent Homepage UI I want to implement in this also with more Amazing colors hue changes.

**Comment by vedant-jain03** [comment]
@purnima143 If you think This is valid Please assign me as I did this in last Homepage UI

**Comment by purnima143** [comment]
@vedant-jain03 Do u think it's needed for the home page? Can you make the dark mode from the signup sign-in page? Don't show the dark mode button on the homepage.

**Comment by vedant-jain03** [comment]
So I should make dark mode for Sign up and Sign in only?
I think that their is lot missing in Homepage as compared to modern Website like animations, so I think to look more attractive we should definitely go for Dark mode for Homepage. 
My next issue will be of animation of section on Scrolling so that it will look more Professional
What do you think?
Correct me if I am wrong

**Comment by purnima143** [comment]
@vedant-jain03 except homepage place dark mode everywhere...signup sign in, feed page, profile etc
