### ISSUE TITLE
Want to add Social navbar.

### ISSUE THREAD

**Issue by vedant-jain03** [purnima143/Kurakoo#263]
## **Is your feature request related to a problem? Please describe.**

- I Want to add Social navbar section where the links of Social media handles of Kurakoo will be their.

## **Describe the solution you'd like**

_ Using HTML,CSS ,hover effect and Material UI icon

**Comment by codewithvk** [comment]
@vedant-jain03 can you describe more about it?

**Comment by vedant-jain03** [comment]
@codewithvk #204 as I did in this I did this feature in previous HOMEPAGE ui but I wanted to implement same in new UI

**Comment by purnima143** [comment]
@vedant-jain03 Let's skip it for now. We don't have any social media handles
