### ISSUE TITLE
Adding a chatbot

### ISSUE THREAD

**Issue by ChitvanRamani22** [purnima143/Kurakoo#265]
I observed that there is no chatbot in the website which needs to be there as there are lots of benefits of having chatbots like-
client engagement will be increased
service will also be increased
Its trending too.
@purnima143 @codewithvk please assign this to me.

**Comment by himanshujaidka** [comment]
@ChitvanRamani22 I think this feature will implement later once the website will be functional or deployed. Besides this, there are so many other things that need attention.

**Comment by codewithvk** [comment]
@ChitvanRamani22 Also I think that There is no need to use a chatbot for this project. @purnima143 What's your opinion?

**Comment by ChitvanRamani22** [comment]
> @ChitvanRamani22 I think this feature will implement later once the website will be functional or deployed. Besides this, there are so many other things that need attention.

No worries its not necessary that things that you pay attention to would be same for others also. Everyone has different way.
I hope mentors are there to tell all these things.

**Comment by ChitvanRamani22** [comment]
> @ChitvanRamani22 Also I think that There is no need to use a chatbot for this project. @purnima143 What's your opinion?

Ok @codewithvk i thought it you be good to great and guide the user to signup or login first and all those things but its fine we can focus on other things.
