### ISSUE TITLE
adding session management using jwt

### ISSUE THREAD

**Issue by atharvaze** [purnima143/Kurakoo#266]
## **Is your feature request related to a problem? Please describe.**
Persisting session of the user when they log in.
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Session management using jwt. Accessing user information through tokens and user data.

- A clear and concise description of what you want to happen.
- User logs in and gets a token and his session starts.
- Creating a middleware that verifies the token to allow access to the user to protected routes.
- Maintains the session of the user.

**Comment by atharvaze** [comment]
let me work on this issue @purnima143. Im a gssoc participant.

**Comment by codewithvk** [comment]
@atharvaze Go ahead!

**Comment by codewithvk** [comment]
@atharvaze Can you see the codebase once! After that, can you give more clarify this issue?

**Comment by atharvaze** [comment]
It's done already. Closing this issue
