### ISSUE TITLE
Images folder

### ISSUE THREAD

**Issue by ChitvanRamani22** [purnima143/Kurakoo#277]
Creating a images folder inside /client/src/components and updating the routes accordingly.
@codewithvk please assign this to me.

**Comment by codewithvk** [comment]
@ChitvanRamani22 Can you describe more about it???

**Comment by ChitvanRamani22** [comment]
@codewithvk at present the images are not inside a particular folder they are just inside components which make it look a bit messy.
Organizing them inside a image folder would be good.
