### ISSUE TITLE
Want to make Mentor's Profile Cards in Homepage 

### ISSUE THREAD

**Issue by vedant-jain03** [purnima143/Kurakoo#279]
## **Is your feature request related to a problem? Please describe.**

- I want to give Mentor's Cards Section after Our Reach section.

## **Describe the solution you'd like**

- I will make a div and inside that div I will make card Components.

**Comment by vedant-jain03** [comment]
@codewithvk 
Can you please provide me with the mentor's information of this project, so that I can get started with the work.

**Comment by vedant-jain03** [comment]
@codewithvk 
I have one idea 
Should I make one more page named Team where profile cards of Main Mentors and then name and image of All contributors will be their.
I will use github-API to do it and I can implement very easily .
If you allow me I can make whole new page of Team of Kurakoo.

**Comment by codewithvk** [comment]
@vedant-jain03 You can get information of mentor by [here](https://github.com/purnima143/Kurakoo#project-mentors-)
 
Also, You can create an about us page where one section for Project admin and project mentor and the other section is for contributors.

You can get Contributor's name & more info by this [API](https://api.github.com/repos/purnima143/Kurakoo/contributors)
