### ISSUE TITLE
(GSSOC'21) Navbar for website

### ISSUE THREAD

**Issue by AasthaSinha2305** [purnima143/Kurakoo#29]
hello @purnima143 

As a gssoc participant i would like to work on the navbar for the website, 
I will include everything that has been mentioned in the figma.

I would like to work on the navbar for **feed page**. Can you please assign it to me.

**Comment by AasthaSinha2305** [comment]
@purnima143 Sure 👍

**Comment by purnima143** [comment]
## Header & navbar of website
![Feed navbar-dimension](https://user-images.githubusercontent.com/57852378/110727039-8670f680-8240-11eb-88d7-8707b37e4c7e.png)

## Below is the drive link for the required assets
https://drive.google.com/drive/folders/10zXfEF1m_qzyQPKalxEOnp3PNzKDScCL?usp=sharing

**Comment by purnima143** [comment]
@AasthaSinha2305 Let me know if you face the problem anywhere

**Comment by simranbhalla3** [comment]
@purnima143 Please add this issue in gssoc21 label and assign this to me
