### ISSUE TITLE
Design: Signup & login page on figma

### ISSUE THREAD

**Issue by purnima143** [purnima143/Kurakoo#3]
-   **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1).
- **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
## Content for signup
    - Name
    - Email id
    - Password
    - confirm password
    - Year/sem
    - College
    - Signup button
    
 ##  Content for login
    - Email id
    - Password
    - Login button
## Any queries?
You can comment it here or in Figma file

**Comment by himanshujaidka** [comment]
is the backend for this project is ready?

**Comment by purnima143** [comment]
@himanshujaidka Nope, not yet. Gonna start everything from scratch.

**Comment by shivani789** [comment]
@purnima143 I have made few changes in the Figma file as I felt are required. Please check whether they are visible and suggest any changes if required.

**Comment by himanshujaidka** [comment]
> @himanshujaidka Nope, not yet. Gonna start everything from scratch.

okay, like to collaborate with this project and I think we need to start with the backend first and for frontend, another repo should be there, in short different repo for frontend and backend code

**Comment by rishitbhojak** [comment]
@purnima143 Can I use Glassmorphic design for the sign up/sign in pages? I'd be happy to contribute to Kurakoo

**Comment by purnima143** [comment]
@rishitbhojak Ya sure, but do you think glassmorphic will work well here?

**Comment by purnima143** [comment]
@himanshujaidka Actually you right we should make separate repo for front and backend. But because it comes under GSSoc Project 21, I kept both the folder in one repo so people can easily access it.

**Comment by rishitbhojak** [comment]
@purnima143 At least we can try. I'll design and send you a rough prototype here itself. Alright?

**Comment by ashish009kum** [comment]
is this issue is still open can I work on this

**Comment by himanshujaidka** [comment]
> @himanshujaidka Actually you right we should make separate repo for front and backend. But because it comes under GSSoc Project 21, I kept both the folder in one repo so people can easily access it.

okay, but for this issue, we need a frontend as well as a backend to, we need a discussion on this

**Comment by himanshujaidka** [comment]
> * **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1).
> * **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
> 
> ## Content for signup
> ```
> - Name
> - Email id
> - Password
> - confirm password
> - Year/sem
> - College
> - Signup button
> ```
> 
> ## Content for login
> ```
> - Name
> - Email id
> - Password
> - confirm password
> - Year/sem
> - College
> - Signup button
> ```
> 
> ## Any queries?
> You can comment it here or in Figma file

login content is the same as signup, @purnima143

**Comment by purnima143** [comment]
> > * **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1).
> > * **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
> > 
> > ## Content for signup
> > ```
> > - Name
> > - Email id
> > - Password
> > - confirm password
> > - Year/sem
> > - College
> > - Signup button
> > ```
> > 
> > 
> > ## Content for login
> > ```
> > - Name
> > - Email id
> > - Password
> > - confirm password
> > - Year/sem
> > - College
> > - Signup button
> > ```
> > 
> > 
> > ## Any queries?
> > You can comment it here or in Figma file
> 
> login content is the same as signup, @purnima143

Updated, thank you😊

**Comment by purnima143** [comment]
> @purnima143 At least we can try. I'll design and send you a rough prototype here itself. Alright?

yes, please work on the above mentioned Figma file

**Comment by aritrochakraborty29** [comment]
Hii.. @purnima143    ..can I contribute on it..?

**Comment by kunal299** [comment]
@purnima143 Hey, can I work on this issue for gssoc'21?

**Comment by maanpatel2492** [comment]
> * **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1).
> * **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
> 
> ## Content for signup
> ```
> - Name
> - Email id
> - Password
> - confirm password
> - Year/sem
> - College
> - Signup button
> ```
> 
> ## Content for login
> ```
> - Email id
> - Password
> - Login button
> ```
> 
> ## Any queries?
> You can comment it here or in Figma file

Hey,I can work on this issue.Assign me if possible.

**Comment by srk224** [comment]
> * **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1).
> * **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
> 
> ## Content for signup
> ```
> - Name
> - Email id
> - Password
> - confirm password
> - Year/sem
> - College
> - Signup button
> ```
> 
> ## Content for login
> ```
> - Email id
> - Password
> - Login button
> ```
> 
> ## Any queries?
> You can comment it here or in Figma file

Hey 
Can I design the UI for login and sign-up page. I have a bit of experience in UI/UX design and I think ill be able to do it........Would love to work on this issue!>?

**Comment by purnima143** [comment]
Those who are interested in this issue can start working.I will choose the design.

**Comment by purnima143** [comment]
There are a lot of people for this issue, you can create another issue based on designing related to any features which you think it's needed for the site.

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021.
Thank you.

**Comment by thaditi** [comment]
> * **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1).
> * **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
> 
> ## Content for signup
> ```
> - Name
> - Email id
> - Password
> - confirm password
> - Year/sem
> - College
> - Signup button
> ```
> 
> ## Content for login
> ```
> - Email id
> - Password
> - Login button
> ```
> 
> ## Any queries?
> You can comment it here or in Figma file

Hey @purnima143 , I made this signup and login page on Figma. Please Review. [link](https://www.figma.com/proto/Ia0U0WxzBIZx7gy8QN4sNv/Kurakoo?node-id=1%3A40&viewport=-171%2C382%2C0.579899787902832&scaling=scale-down)

**Comment by thaditi** [comment]
Hey @purnima143 , I made this signup and login page. Please review and suggest any changes that need to be made. [link](https://www.figma.com/proto/Ia0U0WxzBIZx7gy8QN4sNv/Kurakoo?node-id=1%3A40&viewport=-171%2C382%2C0.579899787902832&scaling=scale-down)

**Comment by prerna2712** [comment]
May I work on this under GSSOC '21?

**Comment by codewithvk** [comment]
@purnima143 could you please add gssoc21 tag in this issue!

**Comment by purnima143** [comment]
> Hey @purnima143 , I made this signup and login page. Please review and suggest any changes that need to be made. [link](https://www.figma.com/proto/Ia0U0WxzBIZx7gy8QN4sNv/Kurakoo?node-id=1%3A40&viewport=-171%2C382%2C0.579899787902832&scaling=scale-down)

Great work😊!! But can you copy your frame and paste here[figma link](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo)
Don't forget to comment down your GitHub id and your contribution in the Figma file.

**Comment by purnima143** [comment]
@aritrochakraborty29 @kunal299 @prerna2712 @maanpatel2492  You guys can start contributing😊. But not in this issue, try to create a new issue and once I'll assign you guys can start contributing.

**Comment by thaditi** [comment]
> > Hey @purnima143 , I made this signup and login page. Please review and suggest any changes that need to be made. [link](https://www.figma.com/proto/Ia0U0WxzBIZx7gy8QN4sNv/Kurakoo?node-id=1%3A40&viewport=-171%2C382%2C0.579899787902832&scaling=scale-down)
> 
> Great work😊!! But can you copy your frame and paste here[figma link](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo)
> Don't forget to comment down your GitHub id and your contribution in the Figma file.

I have added my frames in the given Figma file.

**Comment by purnima143** [comment]
@all-contributors please add @thaditi  for design

**Comment by thaditi** [comment]
@purnima143 will this be counted as my contribution for GSSOC'21?
