### ISSUE TITLE
Add Google Authentication to SignUp!🚀

### ISSUE THREAD

**Issue by bhubesh757** [purnima143/Kurakoo#31]
@purnima143 After the Completion of **Signup/SignIn** , Just I will Add the Auth to the , So  they can Easily login using Google , Github , Linkedin , And also we can Get the users data with permission
You can Assign this to me After complletion of singup form

**Comment by purnima143** [comment]
Ya sure, after completion of the Signup/Sign in form

**Comment by subhasmitapradhan** [comment]
I would like to work on this issue. Please kindly assign it to me.

**Comment by Sandi-09** [comment]
can i work on this issue?

**Comment by Hardik-07** [comment]
If this issue not assigned, else I would like to work on this.

**Comment by purnima143** [comment]
@bhubesh757 Wanna contribute in this issue?

**Comment by bhubesh757** [comment]
@purnima143 yes

**Comment by purnima143** [comment]
@bhubesh757 Go ahead

**Comment by bhubesh757** [comment]
@purnima143  sorry for the late reply , can i use firebase , it makes easy ! with simple lines of code

**Comment by subhangi2731** [comment]
@purnima143 please assign this issue to me I want to work on this and will send a pr in 1 day
