### ISSUE TITLE
Frontend: Create a reducer for Alerts 

### ISSUE THREAD

**Issue by sachinsom93** [purnima143/Kurakoo#32]
## **Is your feature request related to a problem? Please describe.**

- Creating a Alert reducer would be helpful to use whenever we want to add a alert in frontend.

## **Describe the solution you'd like**

- I will create a alert reducer that would call whenever we want to use a alert.

@purnima143 could you please assign this to me ?

**Comment by purnima143** [comment]
@sachinsom93 Ya go ahead
