### ISSUE TITLE
search answers based on various parameters (backend)

### ISSUE THREAD

**Issue by mitalirs** [purnima143/Kurakoo#328]
## **search answers based on various parameters**

- Currently, a user does not have the facility to search answers based on various parameters

## **Describe the solution you'd like**

- a route which will fetch answers based on the query string. Following parameters can be used while searching:
1. createdBy
2. tags
3. question id
- currently, the 'tags' field (in the answer model) is currently a string field. I will change it to an 'array of strings' field, this will store various tags in an array. e.g. instead of 'tag1 tag2' it will store [ 'tag1', 'tag2' ] so that process of filtering becomes easier

**Comment by purnima143** [comment]
@mitalirs OK you can work
