### ISSUE TITLE
tags in question model and sorted answers (backend)

### ISSUE THREAD

**Issue by mitalirs** [purnima143/Kurakoo#330]
## **'tags' field in question model and sorted answers**

- Currently, the 'getAnswers' route fetches answers and returns them in a random order
- 'tags' field in 'question' model is a string field

## **Describe the solution you'd like**

- sort the answers fetched by 'getAnswers' route (for a particular question) based on the number of upvotes
- make the 'tags' field to an 'array of strings' field so that all tags are distinctly stored 
- after changing the 'tags' field, make the corresponding changes to 'searchQuestions' route

**Comment by purnima143** [comment]
@mitalirs go ahead
