### ISSUE TITLE
Backend: Discussion on admin

### ISSUE THREAD

**Issue by himanshujaidka** [purnima143/Kurakoo#342]
How to signup for admin? I have not found a post request for the admin, so how to register admin in a database? If this will be verified then pls assign this to me

**Comment by Subham142** [comment]
what I had in my mind was just make a user and make him/her as an admin using postman and that admin can make others as admin. I have put the issue for it. it will save us time.
What's your thought on this @himanshujaidka  @codewithvk ?

**Comment by himanshujaidka** [comment]
Sorry, I didn’t get your point @Subham142
It is just a simple we have to create a route which allows for the admin/signup and in controller we have to put a simple condition which checks if the req is coming from api/signup then it will perform respectively and store the data of admin corrosponding

**Comment by Subham142** [comment]
Seems fair....

.. please do the required changes

**Comment by himanshujaidka** [comment]
@codewithvk pls assign

**Comment by codewithvk** [comment]
@himanshujaidka We can use conditional rendering for login admin.

**Comment by himanshujaidka** [comment]
yes @codewithvk pls assign
