### ISSUE TITLE
Comments (backend)

### ISSUE THREAD

**Issue by mitalirs** [purnima143/Kurakoo#345]
## **Is your feature request related to a problem? Please describe.**

- Currently, users cannot comment their opinions on a particular response/answer
 
## **Describe the solution you'd like**

- Create a 'Comments' model with the fields:
1. createdBy (ref to User model)
2. text (string)
3. concernedAnswer (ref to answer model)
 - creating corresponding controller+route files
 - create a 'writeComment' route that will allow authenticated users to comment on answers based on answerId

**Comment by purnima143** [comment]
@mitalirs okkk assigned to you
