### ISSUE TITLE
proposal: Automatic mails

### ISSUE THREAD

**Issue by himanshujaidka** [purnima143/Kurakoo#367]
## Proposal
With the use of nodemailer, I want to add utility for this project, i.e. after successful signup, the user will get a signup mail from the kurakoo team.

###### Do you want to work on it? - [Yes/No]
Yes, I want to work on this issue

**Comment by codewithvk** [comment]
@himanshujaidka Do you wanna use free service or paid?

**Comment by himanshujaidka** [comment]
> @himanshujaidka Do you wanna use free service or paid?

free service and I think it is offered by the nodemailer package
