### ISSUE TITLE
Design a Landing/Home page for the website

### ISSUE THREAD

**Issue by anhushree** [purnima143/Kurakoo#37]
## **Is your feature request related to a problem? Please describe.**
The website currently does not have a Landing page to explain what it is

## **Describe the solution you'd like**
- The solution is to design a Landing page

**Comment by anhushree** [comment]
I would like to take upon this issue @purnima143

**Comment by purnima143** [comment]
@anhushree  Ya go ahead, Try to create abstract designs and use Unsplash images if you're placing an image. It's a landing page so try to be creative😊. And let me know if you need any help

**Comment by anhushree** [comment]
Okay, Thank you @purnima143.

**Comment by anhushree** [comment]
I have completed, kindly check figma @purnima143

**Comment by purnima143** [comment]
Good work👏, really like the illustrations🙂

**Comment by purnima143** [comment]
@all-contributors please add @anhushree  for design
