### ISSUE TITLE
Redesigning the Feed page in Figma

### ISSUE THREAD

**Issue by anhushree** [purnima143/Kurakoo#38]
## **Is your feature request related to a problem? Please describe.**
- The feed page's design can be improved 

## **Describe the solution you'd like**
- The background of the Logo should be transparent 
- The search bar should be positioned and Add a search icon 
- The elements in Navbar can have icons

**Comment by anhushree** [comment]
I would like to take up this issue @purnima143

**Comment by Ayushbajpai19** [comment]
Can you assign this issue to me, once approved I can start working on it under GSSOC'21.

**Comment by purnima143** [comment]
@anhushree and @Ayushbajpai19  you both can work on design and please make sure to add the images in assets folder

**Comment by anhushree** [comment]
Thank you so much

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by anhushree** [comment]
@purnima143 
![image](https://user-images.githubusercontent.com/56672958/114503898-a171c480-9c4b-11eb-94df-0de48418ed9e.png)


I have modified it a little bit, Kindly check it.

https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1
ArtBoard Name:Feed page(Main)-yellow

**Comment by anhushree** [comment]
@let me know what to do next, if this design is agreed can I merge the PR?
