### ISSUE TITLE
Backend: Setup for Backend(server)

### ISSUE THREAD

**Issue by purnima143** [purnima143/Kurakoo#39]
Need a proper setup for **backend(server)** .  All the directories present are not working because of some issue. I want anyone to help in this issue that has a **proper backend folder/files from scratch**. So that other contributors can start working on Backend without any bugs and errors.

**Comment by promaroy** [comment]
Can I work on this?

**Comment by purnima143** [comment]
@promaroy  Ya

**Comment by purnima143** [comment]
I will assign you for this issue

**Comment by himanshujaidka** [comment]
assign it to me also @purnima143

**Comment by Mayank0255** [comment]
Can you assign this to me as refactor is required to this?

@purnima143
