### ISSUE TITLE
Design:Main feed page(Post card for asking questions)

### ISSUE THREAD

**Issue by purnima143** [purnima143/Kurakoo#4]
-   **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1
).
- **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
## Content for Feed page: Post card
    - Name
    - Questions ask
    - answer,like,share button
    - date of post
    
Take reference of below design
    
 ![Feed (1)](https://user-images.githubusercontent.com/57852378/106391014-37e66600-6411-11eb-82aa-8a7af88a04e6.png)

## Any queries?
You can comment it here or in Figma file

**Comment by RuchiGitHu** [comment]
Hi @purnima143 , does it should be connect and categories section as well in left and right of the feed page as you didn't mention it in "Content for Feed page" comment. Please let me also know about the header and footer section for a page....
Looking forward for contributing here...

**Comment by chehak123** [comment]
Hi, I want to work on it as a participant in GSSOC'21, can you please assign this issue to me?

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021.
Thank you.

**Comment by Ayushisood** [comment]
Hii @purnima143 
I would love to contributing to this task as a GSSOC'21 participant.
Kindly assign this task to me.

**Comment by purnima143** [comment]
@RuchiGitHu @chehak123  @shairanshrawat  @Ayushisood  Go ahead with this issue. Use the above Figma file for contribution and don't forget to comment your **GITHUB ID** and **WHAT CONTRIBUTION YOU MADE** on Figma. If you don't comment it won't be considered.

**Comment by purnima143** [comment]
Try to use all your creative here

**Comment by Ayushisood** [comment]
> Try to use all your creativity here...Good luck😊

Thank you maam!

**Comment by shairanshrawat** [comment]
> Try to use all your creativity here...Good luck😊

Thank you ma'am

**Comment by encodeArnab** [comment]
Hi @purnima143 , I'm a GSSOC'21 participant with a great website design concept (Main Feed Page) Is it possible for me to work on this problem?
Is it necessary for me to make changes to the Figma file given here, or should I create one and work on the designs there and send you a link?

**Comment by purnima143** [comment]
@encodeArnab It is necessary to use the given Figma link for creating the design otherwise won't count. So, please work on that file only. Once you are done use the comment box and mention your github id and your contribution.

**Comment by purnima143** [comment]
> > Try to use all your creativity here...Good luck😊
> 
> hey @purnima143, I made this Main feed page. Please review and suggest any changes that need to be made [Figma link](https://www.figma.com/file/uDW4JNK3RkxBSPEyaQfFD9/Kurakoo-GSSoc?node-id=0%3A1rl)

@shairanshrawat Sorry but nothing is visible🙁. And please use the provided Figma file, no need to create a new one. If you had created one then copy the complete frame and paste it on the provided Figma file.

**Comment by shairanshrawat** [comment]
> > > Try to use all your creativity here...Good luck😊
> > 
> > 
> > hey @purnima143, I made this Main feed page. Please review and suggest any changes that need to be made [Figma link](https://www.figma.com/file/uDW4JNK3RkxBSPEyaQfFD9/Kurakoo-GSSoc?node-id=0%3A1rl)
> 
> @shairanshrawat Sorry but nothing is visible🙁. And please use the provided Figma file, no need to create a new one. If you had created one then copy the complete frame and paste it on the provided Figma file.

sorry for the inconvenience @purnima143, now have a look I had done it in the main Figma file. Lemme know if I have to change anything

**Comment by purnima143** [comment]
Great work👏 @shairanshrawat Just copy your frames to the given Figma file and comment down your GitHub id and about your contribution there.

**Comment by shairanshrawat** [comment]
> Great work👏 @shairanshrawat Just copy your frames to the given Figma file and comment down your GitHub id and about your contribution there.

**Comment by RuchiGitHu** [comment]
> * **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1).
> * **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
> 
> ## Content for Feed page: Post card
> ```
> - Name
> - Questions ask
> - answer,like,share button
> - date of post
> ```
> 
> Take reference of below design
> 
> ![Feed (1)](https://user-images.githubusercontent.com/57852378/106391014-37e66600-6411-11eb-82aa-8a7af88a04e6.png)
> 
> ## Any queries?
> You can comment it here or in Figma file

Hi @purnima143, as I new to use figma but I have desire to learn it. Please guide me to understand it better.
I have certain doubt, please help me to overcome from this...
Can I directly edit/design main feed page in figma file?
Thanks in advance...

**Comment by purnima143** [comment]
take the above image as a reference and design by your own thoughts

**Comment by purnima143** [comment]
Those who contributed to Figma. Please create a pr and insert the image in the assets folder of the repo.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by RuchiGitHu** [comment]
> > * **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1).
> > * **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
> > 
> > ## Content for Feed page: Post card
> > ```
> > - Name
> > - Questions ask
> > - answer,like,share button
> > - date of post
> > ```
> > 
> > 
> > Take reference of below design
> > ![Feed (1)](https://user-images.githubusercontent.com/57852378/106391014-37e66600-6411-11eb-82aa-8a7af88a04e6.png)
> > ## Any queries?
> > You can comment it here or in Figma file
> 
> Hi @purnima143, as I new to use figma but I have desire to learn it. Please guide me to understand it better.
> I have certain doubt, please help me to overcome from this...
> Can I directly edit/design main feed page in figma file?
> Thanks in advance...

Please check my feed page, I have commented in figma file. @purnima143

**Comment by RuchiGitHu** [comment]
> Those who contributed to Figma. Please create a pr and insert the image in the assets folder of the repo.

Ok @purnima143, please review my PR #127.
Thanks in advance..
