### ISSUE TITLE
Frontend useredit

### ISSUE THREAD

**Issue by ChitvanRamani22** [purnima143/Kurakoo#401]
The UI of useredit screen is completly messed up as shown i would like to design it properly, and also add show/hide password feature in the same.
![20210525_202541.jpg](https://user-images.githubusercontent.com/68965499/119520421-e5ea9700-bd97-11eb-99e5-077f063b5750.jpg)

###### Do you want to work on this issue - [Yes/No]yes
    @codewithvk please assign this to me.

**Comment by codewithvk** [comment]
Gssoc
