### ISSUE TITLE
get notification + create notification

### ISSUE THREAD

**Issue by mitalirs** [purnima143/Kurakoo#436]
## **Is your feature request related to a problem? Please describe.**

- currently, there is no notifications feature

## **Describe the solution you'd like**

- get a notification by id 
- create a notification when a user answers your question
- create a notification when a user comments on your answer

###### Do you want to work on this issue - [Yes/No] - Yes

**Comment by Subham142** [comment]
I also just had this idea,  when I came to propose it.

i was beaten 2 hours before  :)

**Comment by himanshujaidka** [comment]
@mitalirs so how do we send notifications? via mail?

**Comment by codewithvk** [comment]
@mitalirs Please specify, Which type of notification do you want to implement, also share a little bit of approch.

**Comment by mitalirs** [comment]
a user will be notified when someone:
1. answers their qs
2. comments on an ans that the user created
3.  upvotes their ans/qs/comment
4. downvotes their ans/qs/comment

basically, I will create a notification model that will store the notifications for a user the fields would be:
1. notificationFor (the id of user who is supposed to be notified)
2. notificationTitle: string field
3. upvoteCommentNotification (will store the id of comment which was upvoted)
4. upvoteQsNotification (will store the id of qs which was upvoted)
5. upvoteAnsNotification (will store the id of ans which was upvoted)
6. ansNotification (an object that will contain the id of answer that was created (by some user) + id of qs (created by user))
7. commentNotification (an object that will contain the id of comment that was created (by some user) + id of ans (created by user))
8.  status (read/unread)

- the fields numbered from 3 to 7 will not have "required" set to true, so that a new notification object can be accordingly created based on type of notification
- and these fields (3-7) will give the user an extra detail as the user will be able to get the particular entity with the id that was sent as a part of notification

a user can fetch all his/her notifications by /getNotifications route
to mark a particular notification as "read", a user will have use the /getNotification/:id route (get notif by id)

this issue was about creating a notification object when someone comments on your ans/answers your qs and to fetch a notification by id

and issue #435 was about creating the Notification model and a getNotifications route that would have fetched a list of unread notifications 

Also, I am sorry for not mentioning proper details

> @mitalirs Please specify, Which type of notification do you want to implement, also share a little bit of approch.

**Comment by codewithvk** [comment]
@mitalirs Sounds good! Go ahead and if you need some help, ping me on discord.
