### ISSUE TITLE
Design: Make feed page(Categories and follow part)

### ISSUE THREAD

**Issue by purnima143** [purnima143/Kurakoo#5]
-   **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1
).
- **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
## Content for Feed page: Categories
    - Categories on left side
 ## Content for Feed page: Follow others
    - List all user names with profile pic on right side
    
Take reference of below design
    
 ![Feed (1)](https://user-images.githubusercontent.com/57852378/106391014-37e66600-6411-11eb-82aa-8a7af88a04e6.png)

## Any queries?
You can comment it here or in Figma file

**Comment by Aniket1103** [comment]
I will like to work on this issue, please assign it to me.

**Comment by Aniket1103** [comment]
@purnima143 In which folder should I keep the feedPage component ?
In  src->components->common or  src->components ?

**Comment by kunal299** [comment]
@purnima143 Can I work on this for gssoc'21?

**Comment by chehak123** [comment]
Hi, I want to work on it as a participant in GSSOC'21, can you please assign this issue to me?

**Comment by shawavisek35** [comment]
Hey, I would like to work on this issue as a participant in GSSOC'21.

**Comment by Aniket1103** [comment]
@purnima143 I have designed some basic prototype for the feed page in the Figma file, please check that out and suggest changes (if any)

**Comment by purnima143** [comment]
@Aniket1103  Ya thanks for your contribution. One important instruction, Please **USE COMMENT BOX** and **WRITE YOUR GITHUB USERNAME+WHICH COMPONENT YOU WORKED ON.** Otherwise it'll create conflicts.

**Comment by Aniket1103** [comment]
@purnima143 You are talking about the **comment box in Figma**, right?
or over here I have to comment **(in the Github comment box)**?
Anyway I have added a comment in the Figma file

I had a query:
When will you assign us for the frontend part?
Will, there be different issues for it or you will be assigning the feed page frontend part to someone amongst the commenters of this issue only?

**Comment by purnima143** [comment]
@Aniket1103  I will assign for the front end part.I assigned a few people. If you want to work on the front end part of the feed then create a new issue by saying" Front end: Feed page".We suppose to follow the First come first serve method, only those will assign. If the assigned person failed to made PR within a week then the chance will get to the next commenter. Only in the design field, multiple people are allowed.

**Comment by encodeArnab** [comment]
@purnima143  Greetings! I created the categories, connect and home page in this [Figma file](https://www.figma.com/file/cErrvjNvI4R4CxhljAagbl/Kurakoo-Main?node-id=0%3A1); could you please review it before I add it to the Kurakoo Figma File? 
Thank you so much.

**Comment by kaffan** [comment]
Hey @purnima143 am a gssoc participant please assing me this issue

**Comment by foram-s1** [comment]
I would like to contribute to this. Can I @purnima143 ?

**Comment by purnima143** [comment]
Those who contributed to Figma. Please create a pr and insert the image in the assets folder of the repo.
