### ISSUE TITLE
Changes and fixes on the Front-end Homepage.

### ISSUE THREAD

**Issue by shivamp296** [purnima143/Kurakoo#504]
**### Minor Problem.**
1) Login and sign-up buttons are slightly out of body.
2) The hovering effect of both of them does not comply with the orange background.
3) In side navbar - there is small gap between whatsapp and facebook icon.
4) The email box inside the footer , have send button unintended.

I want to work on , the login and sign up positioning , and changing it's hovering effect as well as text decoration , want to fix the gap of side navbar and make minor changes and want to position the send button of the email text-bar inside the footer and resize it.

**Comment by purnima143** [comment]
@shivamp296  go ahead
