### ISSUE TITLE
Backend: Admin signup failed

### ISSUE THREAD

**Issue by kaustubhai** [purnima143/Kurakoo#524]
## **Describe the bug**
Admin required fields are not being fetched from user as payload. Missing keys are 
- location
- joiningDate
- educationalQualification
- description

## **Possible solution**
Either add them to payload of the api as required
Or remove the required from Model

###### Do you want to work on this issue - [Yes/No]
Yes

**Comment by GabriFedi** [comment]
I'm interested in working on this issue

**Comment by RiteshKr00** [comment]
I would like to Work on this

**Comment by purnima143** [comment]
@GabriFedi Assigning you

**Comment by kaustubhai** [comment]
@purnima143 if you'll see I already had done it in a PR #525
