### ISSUE TITLE
Adding Footer with some styling (Frontend)

### ISSUE THREAD

**Issue by ankitaugale23** [purnima143/Kurakoo#54]
Footer will be having contact information and other basic things which standard footers have with some styling to it with color code closely related to our logo.

**Comment by ankitaugale23** [comment]
I would like to work on this. If you have any styling or the format in mind please let me know. I will work with that.

**Comment by purnima143** [comment]
@ankitaugale23  Go ahead

**Comment by purnima143** [comment]
@ankitaugale23  Are you working on the frontend or design? Please mention your issue title also.

**Comment by ankitaugale23** [comment]
Sorry for the late reply. I am working on the front end. 
Sure I will mention in the issue title
Do you have any specific design in your mind for the footer? or should I work directly on my own idea? @purnima143

**Comment by kanishkaa24** [comment]
Hello Mam! Can I work on this?

**Comment by ankitaugale23** [comment]
Should I proceed with my idea for this issue @purnima143 or shall I wait till you give me a specific design?

**Comment by 435akashjha** [comment]
@purnima143 Can I work on this issue

**Comment by ShambhaviSharma0110** [comment]
hey, I've added the footer please review the pr...
