### ISSUE TITLE
[Design] -  UI Design for Notifications Page

### ISSUE THREAD

**Issue by encodeArnab** [purnima143/Kurakoo#55]
## **Is your feature request related to a problem? Please describe.**

- For the 'notifications page', there are no UI designs.

## **Describe the solution you'd like**

- This page's UI designs are something I'd like to focus on.

**Comment by purnima143** [comment]
@encodeArnab Go ahead

**Comment by encodeArnab** [comment]
Thank You @purnima143 😃

**Comment by purnima143** [comment]
@encodeArnab  Please create a pr and insert the image in the assets folder of the repo.

**Comment by kanishkaa24** [comment]
Hello Mam! Can I work on this?

**Comment by manognyaa** [comment]
@purnima143 Can I also contribute to this issue ?

**Comment by encodeArnab** [comment]
> @encodeArnab Please create a pr and insert the image in the assets folder of the repo.

Okay I will surely do that.

**Comment by encodeArnab** [comment]
Hello @purnima143, I have created a PR regarding Home Page, Profile Page and Notifications Page.
For Notifications Page, Please review it once here [Notifications Page In Figma](https://www.figma.com/file/GKl627y9wfjOBDONSby3HE/Kurakoo-Notifications-Page?node-id=0%3A1)
Thank You
