### ISSUE TITLE
Design:Profile page

### ISSUE THREAD

**Issue by purnima143** [purnima143/Kurakoo#6]
-   **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1
).
- **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
## Content for Profile page
    - Profile pic with camera icon at the bottom right corner of the pic
    - Cover photo
    - Name
    - College
    - Year/Branch
    - Question ask tab
    - Answer tab
    - Follow button 
    
Take reference of below design
    ![Profile page](https://user-images.githubusercontent.com/57852378/106391287-92cc8d00-6412-11eb-8979-6b921ad4e16a.png)

## Any queries?
You can comment it here or in Figma file

**Comment by shivani789** [comment]
Follow button should only come when viewing other's profile, not in the user profile.
And also the total number of followers and following should be displayed on the profile.

**Comment by mohdarif8299** [comment]
Can I work on it?

**Comment by kunal299** [comment]
@purnima143 Can I take this issue as a part of Gssoc'21?

**Comment by chehak123** [comment]
Hi, I want to work on it as a participant in GSSOC'21, can you please assign this issue to me?

**Comment by purnima143** [comment]
@mohdarif8299  @kunal299 @chehak123 GSSOC'21  not yet started. If you work now, it won't be counted for the program. Most probably they will start from 8th of March. So, have patience...think of design and let me know your ideas here. Once Gssoc starts I'll assign you guys😊

**Comment by Devenkapoor7303** [comment]
@purnima143 Can I work on this issue as a part of Gssoc as it has started ?

**Comment by purnima143** [comment]
ya...Those who are interested in this go ahead. I will select the design. There are a lot of people on this issue. Please try to create more issue related to design for the site and then I will assign that issue.

**Comment by Esha-Sherring** [comment]
I would like to solve this issue as a participant of GSSoC'21

**Comment by mridulabatra** [comment]
hello mam, I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by Ayushisood** [comment]
Hii @purnima143 
I would like to contribute to this task as a participant of GSSOC'21

**Comment by purnima143** [comment]
@Esha-Sherring  @mridulabatra  @Ayushisood  Please go ahead with designing

**Comment by SARVESHKHANDELWAL** [comment]
Hii @purnima143
I would like to work on this issue can you please assign me.

**Comment by dishiita** [comment]
Hello @purnima143 I would also like to work on this issue

**Comment by pshivesh8** [comment]
As a GSSOC'21 participant, I would love to work on this issue. I have previously worked with HTML, CSS, React JS, Node JS as well as Bootstrap. Could you please assign this issue to me?
Thank you!!

**Comment by purnima143** [comment]
Any update on profile page designing?

**Comment by dishiita** [comment]
@purnima143 I am working on it. Would be completed mostly by today

**Comment by purnima143** [comment]
@dishitta Cool👍

**Comment by encodeArnab** [comment]
Hello @purnima143 I didn't know that I have to make changes in this Figma file only.
so I have created one and made changes here, kindly review it after then I will add it to that Figma file,  
[Figma Designs](https://www.figma.com/file/eKJHIq1klPx5MwwZrRn1zI/Kurakoo-Profile?node-id=0%3A1)  
Thank You

**Comment by purnima143** [comment]
@encodeArnab Great job, I really like the design😊😍. But can you pls copy and paste the frames on the provided Figma file and comment your GitHub id and your contribution there.

**Comment by encodeArnab** [comment]
Thank You @purnima143 😄😃
Okay I will do it now.

**Comment by encodeArnab** [comment]
I have added the designs to the Figma file as mentioned
Thank You 😄

**Comment by purnima143** [comment]
@all-contributors please add @encodeArnab  for design

**Comment by purnima143** [comment]
@all-contributors please add @encodeArnab  for design

**Comment by dishiita** [comment]
@purnima143 I have made a design as well. You can have a look here [https://www.figma.com/file/Tw73Aipl2bJ1yGGvOBoFnz/Untitled?node-id=0%3A1](Design). Let me know what changes are needed!

**Comment by kunal299** [comment]
@purnima143 Can I also share a design with you?

**Comment by kunal299** [comment]
As specified, I have used those primary colors and all the content needed. 
![image](https://user-images.githubusercontent.com/71486434/111037155-efc35600-8448-11eb-918d-9364921fc1dc.png)

**Comment by purnima143** [comment]
Those who contributed to Figma. Please create a pr and insert the image in the assets folder of the repo.

**Comment by kunal299** [comment]
@purnima143 I have created a pr. Check it out.
