### ISSUE TITLE
Creating a Sign up page(GSSoC 21)

### ISSUE THREAD

**Issue by kaffan** [purnima143/Kurakoo#62]
## Proposal

(A clear and concise description of what the proposal is.)

The webite of our project will be containing a sign up pagte in order to create an account. 
it will ask for important information like name, mobile no, city, country etc
it will ask to make a username and a password

**Comment by balarka135** [comment]
I like to work on this issue. Pls assign me this project

**Comment by purnima143** [comment]
Done #19
