### ISSUE TITLE
Frontend:Post Question page(gssoc21)

### ISSUE THREAD

**Issue by kaffan** [purnima143/Kurakoo#63]
## Proposal

I would like to design post question page as gssoc21 participant

**Comment by purnima143** [comment]
@kaffan  Go ahead

**Comment by kaffan** [comment]
@purnima143 can i get the figma design for this page

**Comment by purnima143** [comment]
@kaffan Could you wait. I'll create an issue for the post question page design after getting the design you can start working.

**Comment by kaffan** [comment]
@purnima143  ok thanks

**Comment by ShambhaviSharma0110** [comment]
hey, I'm interested in this project could you please allow me to make a pr?

**Comment by kanishkaa24** [comment]
Hello Mam! Can I work on this?
