### ISSUE TITLE
How to setup the application in local machine

### ISSUE THREAD

**Issue by sagar-barapatre** [purnima143/Kurakoo#7]
We can provide in the readme of this project how to setup the project locally in our machine.

**Comment by himanshujaidka** [comment]
@sagar-barapatre first you need to fork this project then clone it to your local machine then run it

**Comment by sagar-barapatre** [comment]
@himanshujaidka I know that. I m telling whenever a beginner tries to work on this project, how should he/ she shoul setup this project on their local machines, that can be provided in the readme

**Comment by vkassingh** [comment]
Hey @purnima143 , I would like to work on this issue as a part of gssoc21. Do we have a discord server for kurakoo ?

**Comment by purnima143** [comment]
@vkassingh  Wait till 1st march

**Comment by ChitvanRamani22** [comment]
Hi @purnima143 , I would like to work on this issue as a part of gssoc21.Can you please assign this to me

**Comment by RuchiGitHu** [comment]
> We can provide in the readme of this project how to setup the project locally in our machine.

Hi @sagar-barapatre , I hope you are doing well...
I can resolve this issue effectively, give me a chance to contribute in this issue....
Thanks in advance...

**Comment by garvitgupta13** [comment]
> We can provide in the readme of this project how to setup the project locally in our machine.

Please assign me this issue. I can fix this issue as a part of gssoc21

**Comment by atharvaze** [comment]
This issue needs a good readme doc. I can do this as a part of gssoc21
