### ISSUE TITLE
Change the favicon and signIn issue

### ISSUE THREAD

**Issue by Subham142** [purnima143/Kurakoo#70]
## **Describe the bug**

->to change the favicon logo as well as the text
-> on clicking the "Sign In" we should be redirected to the sign in page

## **Possible solution**

->add image and text
->use LinkTo 

## **Screenshots**

![Screenshot (37)](https://user-images.githubusercontent.com/60570595/111033744-c6023300-8438-11eb-80c4-a1255cc331d6.png)

**Comment by Subham142** [comment]
I can work on it 
Please add labels and assign them to me

**Comment by purnima143** [comment]
@Subham142 Go ahead
