### ISSUE TITLE
Design: Add Post question page

### ISSUE THREAD

**Issue by purnima143** [purnima143/Kurakoo#75]
-   **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1
).
- **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**

##Take reference from the below design
![image](https://user-images.githubusercontent.com/57852378/111058935-e02f2600-84b7-11eb-9243-46eec932f072.png)

## Any queries?
You can comment it here or in the Figma file

**Comment by kaffan** [comment]
hey @purnima143 how about designing it like stackoverflow page?

**Comment by purnima143** [comment]
> hey @purnima143 how about designing it like stackoverflow page?

@kaffan Ya StackOverflow is also nice, but I like the UX of quora. We could take reference of both the sites.

**Comment by kaffan** [comment]
@purnima143 i can think of design but actually i have never designed any web page using tools like figma. can you give me a little description like what are the essential parts you need in post question page

**Comment by abhinav5481** [comment]
Hi @purnima143 
I would like to work on this issue as part of GSSOC'21. Could you please assign it to me?

**Comment by purnima143** [comment]
@abhinav5481 Ya go ahead

**Comment by purnima143** [comment]
Those who contributed to design. Please create a pr and insert the image in the assets folder of the repo.

**Comment by kanishkaa24** [comment]
Hello Mam! Can I work on this?

**Comment by nishantsahu961** [comment]
@purnima143 , I would like to contribute in this feature as a Gssoc participant , Can i work upon the issue ?

**Comment by Chadha93** [comment]
@purnima143 As I have also designed the question page earlier so I also designed the Add Post question page accordingly
