### ISSUE TITLE
Design:Question page

### ISSUE THREAD

**Issue by purnima143** [purnima143/Kurakoo#76]
-   **UI Prototyping** with figma tool [figma design](https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1
).
- **Please follow the 3 primary colours - #FFBB00 ,#FF6F00 ,#411818 for designing the pages**
- After clicking on a particular question, a separate page should appear which will have the person name who asked the question,date-time, question, all the answers and a like/dislike button.
## Take reference from the below designs
![image](https://user-images.githubusercontent.com/57852378/111058988-49af3480-84b8-11eb-8e16-4218a115b77d.png)
![Question](https://user-images.githubusercontent.com/57852378/111058994-503dac00-84b8-11eb-833f-4d78bb9eeac3.png)

## Any queries?
You can comment it here or in Figma file

**Comment by bhavesh1334** [comment]
Hello! @purnima143  I would like to work on this issue as a GSSOC_21 participant , Can you please assign it to me.

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by abhinav5481** [comment]
Hi @purnima143 
I would like to work on this issue. Could you please assign it to me?

**Comment by Chadha93** [comment]
@purnima143  I will provide the design max in 2-3 days and I have UI experience in FIGMA you can assign me so I can start

**Comment by purnima143** [comment]
@bhavesh1334 @akshatvirmani @abhinav5481 @Chadha93 You all can work on this issue.

**Comment by Chadha93** [comment]
@purnima143  here it's done
 https://www.figma.com/file/1gYZlafa8bUZu61ji10unF/Kurakoo?node-id=0%3A1
but how will a pr for figma is created because we don't have to add anything

**Comment by purnima143** [comment]
Those who contributed in design. Please create a pr and insert the image in the assets folder of the repo.

**Comment by Chadha93** [comment]
@purnima143  I have made the pr please review it

**Comment by Chadha93** [comment]
@purnima143 can you please also add me to contributes list in readme
