### ISSUE TITLE
Start the server and client together

### ISSUE THREAD

**Issue by Subham142** [purnima143/Kurakoo#79]
## **Is your feature request related to a problem? Please describe.**

We need to start the frontend and backend separately. This should be fixed

## **Describe the solution you'd like**

Use concurrently

**Comment by Subham142** [comment]
Please assign this to me. and also labels the labels

**Comment by codewithvk** [comment]
@Subham142 go ahead!

**Comment by codewithvk** [comment]
@pronayguha13 Without get assigned for the issue, you can't create PR. it's not valid. so take care of it :)
