### ISSUE TITLE
Proposal: Developing Authentication API Endpoints

### ISSUE THREAD

**Issue by EANimesha** [purnima143/Kurakoo#83]
## Proposal for the User Authentication API Endpoint development.

For the Authentication of the application following APIs need to be created

- /user/signup
- /user/signin
- /user/forget-password

The task breakdown for the authentication function as follows.

- [ ] create User Schema
- [ ] develop user signup endpoint
- [ ] develop user signing endpoint
- [ ] develop forget-password endpoint

**Comment by EANimesha** [comment]
I have added a task breakdown for the development of the authentication APIs. Multiple participants can contribute to this. We can start the development of the server side by assigning each of those tasks as tickets to participants. Suggest if need more features.
Also, I like to develop the signup endpoint & could you please assign it to me.

**Comment by Mayank0255** [comment]
#17 & #59 seems to be of similar kind, you should discuss with there assignees and ask for a collaboration.

**Comment by MoatazNasr** [comment]
I'd like to work on signup endpoint as a GSSOC student .

**Comment by MoatazNasr** [comment]
any updates moderators ??
