### ISSUE TITLE
Replacing body parser with Express' own body parser

### ISSUE THREAD

**Issue by singhayushh** [purnima143/Kurakoo#89]
## Proposal
Hello, for express versions 4.16 and above, express' body parser is included in the default express package and there is no need to install additional body parser dependencies to the application.

I would like to work this issue myself if approved.

**Comment by abhay27chauhan** [comment]
**Describe your Proposal**
Express version 4.16+, their own body-parser implementation is now included in the default Express package so there is no need for you to download another dependency.

You have added a line to your code that looks like the following:

- app.use(bodyparser.json()); 

If you are using Express 4.16+ you can now replace that line with:

- **app.use(express.json());** 

you also have the following code in your environment:

- app.use(bodyParser.urlencoded({extended: true}));

You can replace that with:

- **app.use(express.urlencoded());**

**Comment by abhay27chauhan** [comment]
I am a participant of GSSOC'21. Pls assign this issue to me.

**Comment by singhayushh** [comment]
@abhay27chauhan ??? 
Did you read the issue body?

**Comment by abhay27chauhan** [comment]
@singhayushh yes, i was just proposing what i will do if this issue is assigned to me

**Comment by singhayushh** [comment]
@abhay27chauhan, alright. you may take this issue, I back out for you.

**Comment by abhay27chauhan** [comment]
Pls somebody assign this issue to one of us

**Comment by singhayushh** [comment]
Wow.
