### ISSUE TITLE
I would like to work on the frontend using React JS

### ISSUE THREAD

**Issue by A7abhilash** [purnima143/Kurakoo#9]
I have already made a similar project, do check it out [Edu App](https://github.com/A7abhilash/edu-app).
But it was built using React + Firebase tech stack. As your project is using node and express in the backend, I would like to work on frontend part using React JS and build a neat UI using bootstrap and framer motion. We can get started with basic features to be added and as we move on, we can add more features.
#GSSOC21

**Comment by subhangi2731** [comment]
can you please assign this to me?

**Comment by purnima143** [comment]
@subhangi2731 @A7abhilash  You guys can start creating issue related to front end
