### ISSUE TITLE
Compact Code: Sign In/SIgn Up pages

### ISSUE THREAD

**Issue by vdmondkr2002** [purnima143/Kurakoo#90]
**Proposal:**
More compact react state code in Sign In and Sign Up pages
I noticed that in the code of sign In and sign Up pages on the client side the there have been different states for each input field , instead of which we can use a single state which will be an object 

This will help in making the code much more compact and readable.

I would like to work on this issue @purnima143

**Comment by digbijaya20** [comment]
Please assign it to me

**Comment by vdmondkr2002** [comment]
No i have created this issue @digbijaya20 , please assign it to me @purnima143
