### ISSUE TITLE
Frontend: Homepage for kurakoo

### ISSUE THREAD

**Issue by hardik7e** [purnima143/Kurakoo#96]
## Proposal
I would like to code out the landing page/ HomePage for kurakoo as per this design 
![Kurakoo HomePage1](https://user-images.githubusercontent.com/62202998/111334978-04e2f380-869a-11eb-88d3-f031b9e4a224.PNG)

Please assign it to me

**Comment by ir2010** [comment]
Assigned to you. Go ahead @hardik7e

**Comment by hardik7e** [comment]
Thank you @ir2010

**Comment by Avnish5** [comment]
Kindly assign me this issue under GSSOC 2021.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by sparkler20** [comment]
Issues are to be assigned on first come first serve basis. If a valid PR is not created within 4 days, the issue will be assigned to someone else.

**Comment by ir2010** [comment]
The issues are to be assigned on first come first serve basis. If a valid PR is not made within 4 days, the issue may be assigned to someone else.
