### ISSUE TITLE
Considering using Docker for Development

### ISSUE THREAD

**Issue by jain-rishabh-21** [purnima143/Kurakoo#98]
## **Is your feature request related to a problem? Please describe.**

- Shifting development to docker will help in easing the work for new contributors.
- 
## **Describe the solution you'd like**
Using docker for development will be a good choice. WIll help the contributors start straight with the coding part

**Comment by maw1a** [comment]
Is this required @jain-rishabh-21 ? I feel it's unnecessary considering its a web project.

**Comment by jain-rishabh-21** [comment]
Umm I guess it will be useful, as everyone uses a different OS and some developers using WSL gets a lot of errors while developing, exactly the case with me!

**Comment by jain-rishabh-21** [comment]
@purnima143 , Can you please look into this!
